openapi: 3.0.4
info:
  title: Dear carmate
  version: 1.0.0

server:
  url: "http://localhost:3001"
  description: 로컬 호스트에서 테스트할 때, 사용할 수 있는 기본 서버이다.
  port:
    enum:
      - "3000"
      - "3001"
    default: "3000"

tags:
  - name: customer
    description: customer에 대한 API를 설명합니다.

paths:
  /customer:
    $ref: ./paths/customer/index.yaml
  /customer/{customerId}:
    $ref: ./paths/customer/customerId/index.yaml
  /customer/upload:
    $ref: ./paths/customer/upload/index.yaml

