openapi: 3.0.4
info:
  title: Dear carmate
  version: 1.0.0

server:
  url: "http://localhost:3001"
  description: 로컬 호스트에서 테스트할 때, 사용할 수 있는 기본 서버이다.
  port:
    enum:
      - "3000"
      - "3001"
    default: "3000"

tags:
  - name: customer
    description: customer에 대한 API를 설명합니다.

  - name: car
    description: car에 대한 API를 설명합니다.

  - name: company
    description: company에 대한 API를 설명합니다.


paths:
  /customer:
    $ref: ./paths/customer/index.yaml
  /customer/{customerId}:
    $ref: ./paths/customer/customerId/index.yaml
  /customer/upload:
    $ref: ./paths/customer/upload/index.yaml

  /car:
    $ref: ./paths/car/index.yaml
  /car/{carId}:
    $ref: ./paths/car/carId/index.yaml
  /car/upload:
    $ref: ./paths/car/upload/index.yaml
  /car/models:
    $ref: ./paths/car/models/index.yaml

  /companies:
    $ref: ./paths/company/index.yaml
  /companies/{companyId}:
    $ref: ./paths/company/companyId/index.yaml
  /companies/users:
    $ref: ./paths/company/users/index.yaml

